_wandb:
    value:
        cli_version: 0.23.1
        e:
            jbdcf02x3jf1bxsb2t67quzpz6bd64q8:
                codePath: d:\Project\ACL\my_tool\Tracking_experiments.ipynb
                codePathLocal: Tracking_experiments.ipynb
                cpu_count: 12
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "214748360704"
                        used: "113146408960"
                email: baymaxnguyen306@gmail.com
                executable: d:\Project\ACL\.venv\Scripts\python.exe
                git:
                    commit: c01d421e25e6b54be6c7c4307b152f7a052bb612
                    remote: https://github.com/DLab1402/my_tool
                gpu: NVIDIA GeForce RTX 3050 6GB Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2560
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3050 6GB Laptop GPU
                      uuid: GPU-cd98dfbb-166c-d415-7a67-564938c56298
                host: LAPTOP-FI1VPBM2
                memory:
                    total: "34038341632"
                os: Windows-10-10.0.22621-SP0
                program: d:\Project\ACL\my_tool\Tracking_experiments.ipynb
                python: CPython 3.11.9
                root: d:\Project\ACL\my_tool
                startedAt: "2025-12-19T14:37:33.861372Z"
                writerId: jbdcf02x3jf1bxsb2t67quzpz6bd64q8
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 14
            "4": 3.11.9
            "5": 0.23.1
            "8":
                - 1
                - 3
            "10":
                - 20
            "12": 0.23.1
            "13": windows-amd64
architecture:
    value: cnn2
batch_size:
    value: 64
epoch:
    value: 5
lr:
    value: 0.01
model_para:
    value:
        CNN_channels:
            - 32
            - 64
            - 128
        FC_neurons:
            - 256
            - 128
        input_image_size:
            - 28
            - 28
        input_size: 1
        kernel_size:
            - 3
            - 3
            - 3
        num_CNN_layer: 3
        num_FC_layer: 2
        num_classes: 10
optim:
    value: SGD
